import { useEffect, useState } from 'react'
import AdminSelect from '../../../components/admin/common/AdminSelect.jsx'
import { getReportSummary,getSalesReport,getStockReport,getTopProductsReport } from '../../../services/admin/reportService.js'
import { getApiErrorMessage } from '../../../utils/apiErrors.js'

const iso=(date)=>date.toISOString().slice(0,10)
const defaults=()=>({start_date:iso(new Date(Date.now()-29*86400000)),end_date:iso(new Date())})
const money=(value)=>Number(value||0).toFixed(2)
const label=(value)=>String(value).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const limitOptions=[5,10,20,50].map(value=>({value:String(value),label:`Top ${value}`}))
const statusOptions=[{value:'',label:'All statuses'},{value:'in_stock',label:'In stock'},{value:'low_stock',label:'Low stock'},{value:'out_of_stock',label:'Out of stock'}]

function AdminReportsPage(){
 const [draft,setDraft]=useState(defaults);const [dates,setDates]=useState(defaults);const [limit,setLimit]=useState('10');const [stockSearch,setStockSearch]=useState('');const [stockStatus,setStockStatus]=useState('');const [stockQuery,setStockQuery]=useState('');const [version,setVersion]=useState(0)
 const [summary,setSummary]=useState(null);const [sales,setSales]=useState([]);const [top,setTop]=useState([]);const [stock,setStock]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let mounted=true;Promise.all([getReportSummary(dates),getSalesReport(dates),getTopProductsReport({...dates,limit}),getStockReport({search:stockQuery||undefined,status:stockStatus||undefined})]).then(([a,b,c,d])=>{if(mounted){setSummary(a.data??a);setSales(b.data||[]);setTop(c.data||[]);setStock(d.data||[]);setError('')}}).catch(e=>mounted&&setError(getApiErrorMessage(e,'Reports could not be loaded.'))).finally(()=>mounted&&setLoading(false));return()=>{mounted=false}},[dates,limit,stockQuery,stockStatus,version])
 const applyDates=(e)=>{e.preventDefault();setLoading(true);setDates({...draft})};const reset=()=>{const next=defaults();setDraft(next);setLoading(true);setDates(next)}
 const metrics=summary?[['Total Orders',summary.total_orders,'bi-receipt'],['Gross Sales',money(summary.gross_sales),'bi-cash-stack'],['Net Sales',money(summary.net_sales),'bi-graph-up-arrow'],['Average Order',money(summary.average_order_value),'bi-calculator'],['Pending Orders',summary.pending_orders,'bi-clock'],['Processing',summary.processing_orders,'bi-arrow-repeat'],['Completed',summary.completed_orders,'bi-check-circle'],['Cancelled',summary.cancelled_orders,'bi-x-circle'],['Customers',summary.total_customers,'bi-people'],['Low Stock',summary.low_stock_products,'bi-exclamation-triangle'],['Out of Stock',summary.out_of_stock_products,'bi-box2'],['Reviews',summary.total_reviews,'bi-chat-square-heart'],['Average Rating',Number(summary.average_rating||0).toFixed(2),'bi-star-fill']]:[]
 const maxGross=Math.max(...sales.map(row=>Number(row.gross_sales)),1)
 return <main className="admin-reports-page admin-list-page app-page-shell"><header className="reports-heading admin-list-header app-page-header admin-analytics-header"><div className="admin-list-title-group"><span className="admin-eyebrow app-page-eyebrow">Business intelligence</span><h1 className="app-page-title">Reports & Analytics</h1><p className="app-page-subtitle">Track sales, customers, products, and inventory health.</p></div><button className="admin-refresh-button" type="button" onClick={()=>{setLoading(true);setVersion(v=>v+1)}} disabled={loading} aria-label="Refresh reports"><i className={`bi bi-arrow-clockwise ${loading?'spin':''}`}/></button></header>
 <form className="reports-date-panel admin-filter-card admin-filter-grid app-form-card admin-report-filter-card" onSubmit={applyDates}><label>Start date<input type="date" value={draft.start_date} onChange={e=>setDraft(v=>({...v,start_date:e.target.value}))}/></label><label>End date<input type="date" value={draft.end_date} onChange={e=>setDraft(v=>({...v,end_date:e.target.value}))}/></label><button className="btn btn-admin-primary">Apply Filters</button><button className="btn btn-admin-soft" type="button" onClick={reset}>Reset</button></form>
 {error&&<div className="alert category-alert category-alert-danger"><i className="bi bi-exclamation-octagon"/><span>{error}</span></div>}
 {loading?<div className="reports-loading admin-report-loading">{[1,2,3,4].map(n=><span key={n}/>)}</div>:<><section className="reports-metric-grid admin-report-summary">{metrics.map(([name,value,icon])=><article className="app-stat-card admin-report-metric" key={name}><span><i className={`bi ${icon}`}/></span><div><small>{name}</small><strong>{value}</strong></div></article>)}</section>
 <section className="reports-grid admin-report-grid"><article className="reports-panel app-section-card admin-report-card admin-sales-report-card"><header><div><span>Revenue</span><h2>Sales trend</h2></div><i className="bi bi-graph-up-arrow" aria-hidden="true"/></header>{sales.length===0?<p className="reports-empty admin-empty-state">No sales in this range.</p>:<div className="sales-trend-list">{sales.map(row=><div key={row.date}><span className="admin-report-date">{row.date}</span><b>{row.orders_count} orders</b><div><span style={{width:`${Number(row.gross_sales)/maxGross*100}%`}}/></div><strong className="admin-report-money">{money(row.net_sales)}</strong></div>)}</div>}</article>
 <article className="reports-panel admin-table-card app-section-card admin-report-card"><header><div><span>Performance</span><h2>Top products</h2></div><div className="reports-select"><AdminSelect id="report-limit" name="limit" label="Limit" value={limit} options={limitOptions} onChange={v=>{setLoading(true);setLimit(String(v))}}/></div></header><div className="table-responsive admin-table-wrap"><table className="table reports-table admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Sold</th><th>Sales</th><th>Stock</th></tr></thead><tbody>{top.map((row,index)=><tr key={row.id}><td><div className="admin-report-product"><span className="admin-report-rank">{index+1}</span><strong>{row.name}</strong></div></td><td>{row.sku||'-'}</td><td><strong className="admin-report-quantity">{row.total_quantity_sold}</strong></td><td><strong className="admin-report-money">{money(row.gross_sales)}</strong></td><td>{row.current_stock_quantity}</td></tr>)}</tbody></table></div>{top.length===0&&<p className="reports-empty admin-empty-state">No product sales in this range.</p>}</article></section>
 <section className="reports-panel admin-table-card app-section-card admin-report-card"><header><div><span>Inventory</span><h2>Stock report</h2></div><form className="reports-stock-filters admin-filter-grid" onSubmit={e=>{e.preventDefault();setLoading(true);setStockQuery(stockSearch.trim())}}><input type="search" placeholder="Search product or SKU..." value={stockSearch} onChange={e=>setStockSearch(e.target.value)}/><div className="reports-select"><AdminSelect id="stock-report-status" name="status" label="Status" value={stockStatus} options={statusOptions} onChange={v=>{setLoading(true);setStockStatus(String(v))}}/></div><button><i className="bi bi-search" aria-hidden="true"/> Search</button></form></header><div className="table-responsive admin-table-wrap"><table className="table reports-table admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Stock</th><th>Threshold</th><th>Status</th></tr></thead><tbody>{stock.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.sku||'-'}</td><td>{row.category||'Uncategorized'}</td><td><strong className="admin-report-quantity">{row.stock_quantity}</strong></td><td>{row.low_stock_threshold}</td><td><span className={`report-stock-badge admin-status-badge ${row.stock_status==='in_stock'?'success':row.stock_status==='low_stock'?'warning':'danger'} is-${row.stock_status}`}>{label(row.stock_status)}</span></td></tr>)}</tbody></table></div>{stock.length===0&&<p className="reports-empty admin-empty-state">No stock records match these filters.</p>}</section></>}</main>
}
export default AdminReportsPage
